version: '3'
services:
  first_penguin_test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/first_penguin_test:cached
      # device access
      - /dev:/dev
    working_dir: /workspaces/first_penguin_test
    tty: true
    command: sleep inf
    # device access
    privileged: true
